services:
  book-giveaways-bots:
    build: .
    container_name: book_giveaways
    volumes:
      - .:/app
    # This ensures that if the script crashes, it tries to start again
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles  # Set your local timezone
    ports:
      - "5000:5000"  # Status server dashboard
  
  status-server:
    build: .
    container_name: book_giveaways_status
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - "5001:5001"  # Access status server at http://localhost:5001/
    command: python status_server.py
    environment:
      - TZ=America/Los_Angeles